### ISSUE TITLE
SpatialOmics.from_annData

### ISSUE THREAD

**Issue by seul153** [AI4SCR/ATHENA#9]
Hi.
thank you for very interesting tools.

I tried to check heterogeneity using your tools with visium datasets.
but I couldn't load the dataset.

#visium path.
ex_file = 'Data/Pat_data/HCC1R/'
so =sq.read.visium(path,counts_file = 'filtered_feature_bc_matrix.h5')

image_path = path + '/spatial/tissue_hires_image.png'
img = sq.im.ImageContainer(image_path, img_container=img)

so = SpatialOmics.from_annData(so)

but I got the error.

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[85], line 4
      2 so =sq.read.visium(path,counts_file = 'filtered_feature_bc_matrix.h5')
      3 so
----> 4 so = SpatialOmics.from_annData(so)

File /opt/anaconda/envs/sglee/lib/python3.10/site-packages/spatialOmics/spatialOmics.py:364, in SpatialOmics.from_annData(ad, img_container, sample_id, img_layer, segmentation_layers)
    362     coord = ad.obsm['spatial']
    363     coord = pd.DataFrame(coord, index=so.obs[sample_name].index, columns=['x','y'])
--> 364     so.obs[sample_name] = pd.concat((so.obs[sample_name], coord), 1)
    366 if img_container is not None:
    367     img = img_container[img_layer]

TypeError: concat() takes 1 positional argument but 2 were given

Do you know why this error occurred and how to fix it?

**Comment by adrianomartinelli** [comment]
Hi @seul153 !

thanks for reporting this bug. We are currently migrating ATHENA to AnnData and should release a new version by the end of next week that should make this issue obsolete. I keep you posted.

Best, 
Adriano

**Comment by adrianomartinelli** [comment]
Hi @seul153 
The migration is completed.
If you want to try it out you can install the ATHENA packages with

```
conda create -y -n athena python=3.12
conda activate athena
pip install git+ssh://git@github.com/AI4SCR/ATHENA.git@dev
```

The documentation page is not updated yet but the [tutorial](https://github.com/AI4SCR/ATHENA/blob/dev/tutorials/tutorial.ipynb) is.

Other than that, the arguments to the functions remain the same. Instead of using `function(so=so, spl=spl, ...)` we migrated to `function(ad=ad, ...)`. If you have multiple samples from different Regions of Interest (ROI's) you need to create for each region an own AnnData object. We recommend storing them in a dict like `{<SAMPLE_NAME>: <AnnData>}`.

The framework requires that ['x', 'y'] is in ad.obs. The tutorial shows you how you can extract those centroid coordinates from a segmentation mask. 
If you are using segmentations masks for plotting you have to store it in ad.uns['mask'].

Feel free to reach out with questions.
Best,
Adriano

**Comment by seul153** [comment]
Hi!
Thank you for the update. and I tried with updated athena. but I got the
error.

I think it is the issue with SpatialOmics... Do you know How to solve this
problem?
I have multiple datasets. I want to check for cancer dysplasia with the
evenadml immunity-level step feature.
could you help me work on this?

Thank you :)

Seulgi-Lee

2024년 12월 14일 (토) 오전 1:02, adrianomartinelli ***@***.***>님이
작성:

**Comment by adrianomartinelli** [comment]
Hi,

with the new ATHENA version you do not need `SpatialOmics` anymore. You can directly work with the AnnData object and your segmentation masks or coordinates of the cells. If you can share example data I might be able to give you further pointers.

Maybe as a first step run the tutorial that I linked in my previous response and let me know if you run into some issues there.

Best, Adriano

**Comment by seul153** [comment]
Hi.
Thanks for your reply. and I share my code and can you give some tips for
running athena?

--------------------------------------------------------
## 'ondir' contains several visium datasets.
ondir = '/home/Data_Drive_8TB/sglee/Project/03.hete/Data/Pat_data'
## the substructure is like this.
'''->
/home/Data_Drive_8TB/sglee/Project/03.hete/Data/Pat_data

/home/Data_Drive_8TB/sglee/Project/03.hete/Data/Pat_data/HCC2-R
/home/Data_Drive_8TB/sglee/Project/03.hete/Data/Pat_data/HCC2-R/spatial
/home/Data_Drive_8TB/sglee/Project/03.hete/Data/Pat_data/HCC2-R/filtered_feature_bc_matrix
/home/Data_Drive_8TB/sglee/Project/03.hete/Data/Pat_data/HCC6-NR
/home/Data_Drive_8TB/sglee/Project/03.hete/Data/Pat_data/HCC6-NR/spatial
/home/Data_Drive_8TB/sglee/Project/03.hete/Data/Pat_data/HCC6-NR/filtered_feature_bc_matrix

'''
for path,d,f in os.walk(ondir):
    if 'filtered_feature_bc_matrix.h5' in f:
        adata = sc.read_visium(path,count_file =
'filtered_feature_bc_matrix.h5')
        dataID = path.split('/')[-1]


        ###athena
        image_path = path + '/spatial/tissue_hires_image.png'
        img = sq.im.ImageContainer(image_path)
        #generating object
        adata = sq.read.visium(path,counts_file =
'filtered_feature_bc_matrix.h5')

        so = SpatialOmics.from_annData(adata)
        # compute cell counts
        so.spl['cell_count'] = [len(so.obs[s]) for s in so.obs.keys()]
        so.spl['immune_cell_count'] = [np.sum(so.obs[s].cell_type ==
'immune') for s in so.obs.keys()]

        #if sample-level :
        #so = athena_sp_level(so)

        #else if cell-level:
        #so = athena_c_level(so)

        #else if immune infilt:
        so = ath.neigh.infiltration(so, s, 'cell_type',
graph_key='contact') #athena_Imm_level(so)





2024년 12월 30일 (월) 오전 4:35, adrianomartinelli ***@***.***>님이
작성:
